name: Release

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  docker:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cugu/dashboard
          tag_with_ref: true
